# Generated by Django 4.0.4 on 2023-02-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'ASM',
                'db_table': 'ASM',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Brand',
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Brand_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Brand_Location',
                'db_table': 'Brand_Location',
            },
        ),
        migrations.CreateModel(
            name='Brand_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Brand_type',
                'db_table': 'Brand_type',
            },
        ),
        migrations.CreateModel(
            name='class_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'class_Details',
                'db_table': 'class_Details',
            },
        ),
        migrations.CreateModel(
            name='Light_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Light_Type',
                'db_table': 'Light_Type',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Manager',
                'db_table': 'Manager',
            },
        ),
        migrations.CreateModel(
            name='Material_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Material_Type',
                'db_table': 'Material_Type',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Region',
                'db_table': 'Region',
            },
        ),
        migrations.CreateModel(
            name='RSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'RSM',
                'db_table': 'RSM',
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Showroom',
                'db_table': 'Showroom',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'State',
                'db_table': 'State',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True)),
                ('Visiblity', models.CharField(blank=True, choices=[('Assets', 'Assets'), ('Vendor', 'vendor')], max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Status',
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True)),
                ('Vendor_Comments', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
                'db_table': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='Showroom_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUG_No', models.CharField(max_length=15)),
                ('Landline', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('ASM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.asm')),
                ('Manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.manager')),
                ('RSM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.rsm')),
                ('Region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.region')),
                ('Showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.showroom')),
                ('State', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.state')),
            ],
            options={
                'verbose_name_plural': 'Showroom_Details',
                'db_table': 'Showroom_Details',
            },
        ),
        migrations.CreateModel(
            name='Outlet_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Width', models.CharField(blank=True, max_length=20, null=True)),
                ('Height', models.CharField(blank=True, max_length=20, null=True)),
                ('Asset_Image', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(blank=True, choices=[('Enable', 'Enable'), ('Disable', 'Disable')], max_length=10, null=True)),
                ('Other_Comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('Model_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Expire_On', models.DateField()),
                ('AD_Image', models.ImageField(upload_to='')),
                ('AD_Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Empty Space', 'Empty Space'), ('On Board Escalaton', 'On Board Escalaton')], max_length=50, null=True)),
                ('Brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.brand')),
                ('Brand_Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.brand_location')),
                ('Brand_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.brand_type')),
                ('Light_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.light_type')),
                ('Material_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.material_type')),
                ('Showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.showroom')),
                ('Vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.vendors')),
                ('class_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.class_details')),
            ],
            options={
                'verbose_name_plural': 'Outlet_Media',
                'db_table': 'Outlet_Media',
            },
        ),
        migrations.CreateModel(
            name='full_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.URLField(blank=True, null=True)),
                ('Grade', models.CharField(choices=[('A+', 'A+'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K')], max_length=10)),
                ('Showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Media_Outlet.showroom')),
            ],
        ),
        migrations.CreateModel(
            name='Floor_Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Floor_diagram', models.ImageField(upload_to='')),
                ('Showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.showroom')),
            ],
        ),
    ]
