# Generated by Django 4.0.4 on 2023-02-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Outlet', '0003_rename_name_showroom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet_media',
            name='Asset_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
