# Generated by Django 4.0.4 on 2023-02-14 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Outlet', '0004_alter_outlet_media_asset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ad_Status',
                'db_table': 'Ad_Status',
            },
        ),
        migrations.RemoveField(
            model_name='outlet_media',
            name='AD_Status',
        ),
        migrations.AddField(
            model_name='outlet_media',
            name='Ad_Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.ad_status'),
        ),
    ]
