# Generated by Django 4.0.4 on 2023-02-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Outlet', '0005_ad_status_remove_outlet_media_ad_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet_media',
            name='Expire_On',
            field=models.DateField(blank=True, null=True),
        ),
    ]
