# Generated by Django 4.0.4 on 2023-02-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Outlet', '0006_alter_outlet_media_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom_details',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='showroom_details',
            name='Landline',
            field=models.CharField(max_length=20),
        ),
    ]
