# Generated by Django 4.0.4 on 2023-02-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Outlet', '0007_alter_showroom_details_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom_details',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='showroom_details',
            name='CUG_No',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='showroom_details',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='showroom_details',
            name='Landline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
