# Generated by Django 4.1.7 on 2023-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Outlet', '0010_rename_outlet_media_assetmanagement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmanagement',
            name='AD_Image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetmanagement',
            name='Asset_Image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
