# Generated by Django 4.1.7 on 2023-02-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Outlet', '0011_alter_assetmanagement_ad_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor_diagram',
            name='Floor_diagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
