# Generated by Django 4.0.4 on 2023-02-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Media_Outlet', '0002_alter_floor_diagram_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_By',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Assign_By',
                'db_table': 'Assign_By',
            },
        ),
        migrations.CreateModel(
            name='Assign_To',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Assign_To',
                'db_table': 'Assign_To',
            },
        ),
        migrations.CreateModel(
            name='Design_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Design_Type',
                'db_table': 'Design_Type',
            },
        ),
        migrations.CreateModel(
            name='Job_For',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Job_For',
                'db_table': 'Job_For',
            },
        ),
        migrations.CreateModel(
            name='Job_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], max_length=20)),
                ('Job_For', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Job_Assign.job_for')),
            ],
            options={
                'verbose_name_plural': 'Job_Type',
                'db_table': 'Job_Type',
            },
        ),
        migrations.CreateModel(
            name='Job_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Priority', models.CharField(choices=[('Medium', 'Medium'), ('Top', 'Top'), ('Urgent', 'Urgent')], max_length=20)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Follow Up', 'Follow Up'), ('Completed', 'Completed')], max_length=20)),
                ('Dead_Line', models.DateTimeField()),
                ('Comments', models.CharField(blank=True, max_length=500, null=True)),
                ('Assign_To', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Job_Assign.assign_to')),
                ('Design_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Job_Assign.design_type')),
                ('Job_For', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Job_Assign.job_for')),
                ('Job_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Job_Assign.job_type')),
                ('Showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.showroom')),
            ],
            options={
                'verbose_name_plural': 'Job_Form',
                'db_table': 'Job_Form',
            },
        ),
        migrations.AddField(
            model_name='design_type',
            name='Job_For',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Job_Assign.job_for'),
        ),
        migrations.AddField(
            model_name='design_type',
            name='Job_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Job_Assign.job_type'),
        ),
    ]
