# Generated by Django 4.0.4 on 2023-02-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Assign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign_by',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='assign_to',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='design_type',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='job_for',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='job_type',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='design_type',
            name='Job_For',
        ),
        migrations.RemoveField(
            model_name='design_type',
            name='Job_Type',
        ),
        migrations.RemoveField(
            model_name='job_type',
            name='Job_For',
        ),
        migrations.AlterField(
            model_name='job_form',
            name='Dead_Line',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
