# Generated by Django 4.0.4 on 2023-02-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Domain',
                'db_table': 'Domain',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Resource',
                'db_table': 'Resource',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In-Process', 'In-Process'), ('Created', 'Created')], max_length=50, null=True)),
                ('Rating', models.IntegerField()),
                ('Domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Connect.domain')),
                ('Resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Connect.resource')),
            ],
            options={
                'verbose_name_plural': 'Rating',
                'db_table': 'Rating',
            },
        ),
        migrations.CreateModel(
            name='Assign_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In-Process', 'In-Process'), ('Created', 'Created')], max_length=50, null=True)),
                ('Domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Connect.domain')),
                ('Resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Connect.resource')),
            ],
            options={
                'verbose_name_plural': 'Assign_Job',
                'db_table': 'Assign_Job',
            },
        ),
    ]
