# Generated by Django 4.0.4 on 2023-02-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Connect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='Domain',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='Resource',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='Title',
        ),
    ]
