# Generated by Django 4.0.4 on 2023-02-14 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Connect', '0002_remove_rating_domain_remove_rating_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_job',
            name='Rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Connect.rating'),
        ),
    ]
