# Generated by Django 4.0.4 on 2023-02-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Connect', '0003_assign_job_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Rating',
            field=models.CharField(max_length=1),
        ),
    ]
