# Generated by Django 4.0.4 on 2023-02-13 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Media_Outlet', '0002_alter_floor_diagram_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Type', models.CharField(blank=True, choices=[('Own', 'Own'), ('Rent', 'Rent')], max_length=10, null=True)),
                ('Site_Location', models.CharField(max_length=100)),
                ('Brand_Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Width', models.IntegerField()),
                ('Height', models.IntegerField()),
                ('Start_Date', models.DateField()),
                ('Rent', models.CharField(blank=True, max_length=100, null=True)),
                ('Asset_Image', models.FileField(upload_to='')),
                ('Status', models.CharField(blank=True, choices=[('Enable', 'Enable'), ('Disable', 'Disable')], max_length=10, null=True)),
                ('Other_Comments', models.CharField(blank=True, max_length=500, null=True)),
                ('Model_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('End_Date', models.DateField()),
                ('Rent_Type', models.CharField(blank=True, choices=[('Month', 'Month'), ('Year', 'Year')], max_length=10, null=True)),
                ('AD_Image', models.FileField(upload_to='')),
                ('AD_Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Empty Space', 'Empty Space'), ('On Board Escalaton', 'On Board Escalaton'), ('Approve', 'Approve'), ('BR-Waiting Action', 'BR-Waiting Action'), ('Admin-Job Review', 'Admin-Job Review')], max_length=50, null=True)),
                ('Brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.brand')),
                ('Brand_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.brand_type')),
                ('Light_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.light_type')),
                ('Material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.material_type')),
                ('Vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Media_Outlet.vendors')),
            ],
            options={
                'verbose_name_plural': 'Hoarding',
                'db_table': 'Hoarding',
            },
        ),
    ]
